name: Build Static Website

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test
      run: |
        chmod +x action/minify.sh
        bash action/minify.sh
      shell: bash