name: Build Static Website

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test
      run: ls -la /home/runner/work/static-website-tester/static-website-tester
      shell: bash