name: Build Static Website
description: Automate website optimization

inputs:
  project_path:
    description: Path to the files to minify.
    required: true
    default: '.'
  output_path:
    description: Path of the minified files
    required: true
    default: dist

runs:
  using: composite
  steps:
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install -g html-minifier
        npm install -g clean-css-cli
        npm install -g uglify-js
      shell: bash

    - name: Add action path logging
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: Run Minify Script
      run: bash minify.sh ${{ inputs.output_path }}
      shell: bash

    - name: Upload minified files
      uses: actions/upload-artifact@v3
      with:
        name: minified-files
        path: ${{ inputs.output_path }}